### ISSUE TITLE
Inquiry on Applying TAP for Denoising Real Images

### ISSUE THREAD

**Issue by tiffany-yang** [zfu006/TAP#1]
Dear Author,
Thank you for your excellent work!
I am interested in applying your denoising algorithm to my own real images. 
Could you please provide guidance on how to achieve this?

**Comment by zfu006** [comment]
Do you want to apply TAP to your own images or videos? In raw domain or sRGB domain

**Comment by tiffany-yang** [comment]
Thank you for your prompt response. I appreciate the detailed information you provided. However, I would like to clarify that my intention is to utilize the method within the RGB domain, rather than the sRGB or RAW domains.
Could you please advise if this is feasible, and if so, provide any necessary adjustments or considerations that should be taken into account?

**Comment by zfu006** [comment]
I see, I'll upload the code and pretrained model for sRGB domain, but the pretrained model can only deal with synthetic gaussian noise in sRGB domain. If you want to deal with sRGB real noise, you need to retrain the model with your own datasets
